### ISSUE TITLE
How do I get id (not _id) in the generated schema for --no-mongoose

### ISSUE THREAD

**Issue by akshay-nm** [francescov1/mongoose-tsgen#129]
I want to use id instead of _id in frontend. I am using mongoose-tsgen for types.
I love the project but it restricts me to stick to _id.

**Comment by francescov1** [comment]
Hi @akshay-nm, sorry you can't use the `--no-mongoose` flag in this case, otherwise the generated types would not properly reflect MongoDB documents. 

As a workaround, you can use the following helper type: 

```
type WithId<T> = T & { id: string };

// Example
type UserWithId = WithId<User>
```

Closing for now, but feel free to re-open if you have any questions or suggestions for a feature
