### ISSUE TITLE
Strongly typed method parameters and return types

### ISSUE THREAD

**Issue by LucasRomier** [francescov1/mongoose-tsgen#137]
Hi,

To start off, I am very fond of this extension as it has saved me countless hours of defining my Mongoose Schemas.

Would it however be possible to strongly type the parameters of my schema methods?

E.g., my method is
`getAccessLog(pageSize: number, page: number, sort: "date" | "type" | "value", sortOrder: -1 | 1): Prom`
Currently results in the following under the generated method types
`getAccessLog: (this: IPlanDocument, ...args: any[]) => any;`

Would it be possible, to stronly type this to
`getAccessLog: (this: IPlanDocument, pageSize: number, page: number, sort: "date" | "type" | "value", sortOrder: -1 | 1) => ILog[];`

Thank you for your consideration!

**Comment by francescov1** [comment]
Hi @LucasRomier,

The tool does its best to determine the type of mongoose methods and generate them strongly, but sometimes it cant determine them (eg they are in a format that is not recognized). If you can paste your full schema and method definition, I can do some testing and see whats preventing it from picking the type up properly and try to add support for it.

**Comment by LucasRomier** [comment]
Yes of course, I created a pastebin for you: https://pastebin.com/6yxuPRsR.

In it, I detailed the three additions that I would love to have:
 - Strong typing for method parameters and for the method return types
 - Strong typing for virtual types
 - Strong typing for static method parameters and static method return types

Thank you for your consideration!

Best regards

**Comment by francescov1** [comment]
Sorry for the delay @LucasRomier, planning to look at this over the weekend.

**Comment by francescov1** [comment]
Hi @LucasRomier, I was able to find the problem. Finding types in a file can be a bit tricky due to the variety of ways that TS can be defined. I was able to get your file to generate proper types by making the following changes:

- Export the `Plan` model as a named export. mongoose-tsgen needs to find the line which initializes the model (eg `const Plan: IPlanModel = model<IPlanDocument, IPlanModel>("IPlan", PlanSchema);` but if it is not exported then it is harder)
  - Note: this is actually a flaw of mongoose-tsgen. I will be pushing a fix shortly to address this. So if youd rather keep your exports as is, that should be fine too
- use `Schema.methods = {}`,  `Schema.statics = {}`, etc rather than passing them directly to the schema. This makes it much easier to determine the types.

Lastly, since you are using `Moment` as a return type for your virtual, make sure you use this CLI argument (or option in mtgen.config.json): `--imports "import { Moment } from \"moment-timezone\""`. Usually with import statements its easier to use the mtgen.config.json file, you can see an example in the README.

 Here's the resulting file:

```typescript
import { Schema, model } from "mongoose";
import { IPlanModel, IPlanSchema, IPlanDocument} from "../types/mongoose-types";
import moment, { Moment } from "moment-timezone";
import { pbkdf2, randomBytes } from "crypto";
 
const PlanSchema: IPlanSchema = new Schema({
    expiresOnRaw: {
        type: Date,
        default: undefined
    },
    secret: {
        key: {
            type: String,
            unique: true,
            default: () => randomBytes(64).toString("hex"),
            required: [true, 'Secret must be set'],
        },
        lastKeyChange: {
            type: Date
        }
    },
}, {
    timestamps: true
});

PlanSchema.methods = {
  newKey(key: string): Promise<void> {
    const promise = new Promise<void>(async (resolve, reject) => {
        this.secret.key = await Plan.hashKey(key);
        this.secret.lastKeyChange = new Date();

        try {
            await this.save();
        } catch (err) {
            return reject(err);
        }

        return resolve();
    });

    return promise;
  }
}

PlanSchema.statics = {
  hashKey(key: string): Promise<string> {
    const promise = new Promise<string>((resolve, reject) => {
        pbkdf2(key, "12345", 1, 1, "sha256", async (err, hashed) => {
            if (err) return reject(err);

            resolve(hashed.toString("hex"));
        });
    });
    return promise;
  }
}
 
PlanSchema.virtual("expiresOn").get(function(): Moment | undefined {
    if (!this.expiresOnRaw) return undefined;
 
    return moment(this.expiresOnRaw);
});
 
export const Plan: IPlanModel = model<IPlanDocument, IPlanModel>("IPlan", PlanSchema);
export default Plan;
```

**Comment by francescov1** [comment]
The export fix I mentioned above is now live in v9.2.12, so feel free to update to the latest version and ignore the first bullet point I mentioned!

**Comment by LucasRomier** [comment]
Hi @francescov1,

This is perfect, thank you so much!
Already found three errors where I used Number instead of number 😅...

Best regards!

**Comment by francescov1** [comment]
Type safe mongoose is a game changer 🙌 happy to help!
