### ISSUE TITLE
Is there an up-to date changelog?

### ISSUE THREAD

**Issue by Narretz** [francescov1/mongoose-tsgen#85]
Hi,

I've seen that npm is currently on version 9.0.0, but the changelog in the repo has 8.2.0 as the latest version. There are also no releases on github. Is there another place with an up-to date changelog? If not, could you add the past releases? At the very least, 9.0 would be important as I assume it contains breaking changes.

**Comment by francescov1** [comment]
Hey @Narretz, thanks for pointing this out, been forgetting to update the changelog recently. A bit busy currently but I'll try to get to it next week.

In case you are looking to upgrade sooner, the only reason we bumped to `9.0.0` is a small tweak to the naming convention to better handle plural collection names. If any of your model names end in `ss`, then the generated type names may slightly change, but this should be clear right away with TS. Otherwise, you shouldn't see any breaking changes.

**Comment by francescov1** [comment]
Apologies for the delay, this is updated now!

**Comment by Narretz** [comment]
Thanks!
